variables:
  imageName: 'gosample'
  registry: 'REGNAME.azurecr.io'

stages:
- stage: build
  jobs:
  - job: 'BuildAndPush'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR'
        repository: 'wikimediaACR01'
        command: 'buildAndPush'
        Dockerfile: '**/DockerFile'
        tags: 'wikimedia:$(Build.BuildId)'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'manifests'
        targetPath: $(Build.SourcesDirectory)
